config/routes.rb
NonScaffoldedExample::Application.routes.draw do

  root :to => 'info#index'

  match 'about' => 'info#about', :as => 'about'

  match 'contact' => 'info#contact', :as => 'contact'

  match 'posts' => 'posts#index', :as => 'posts', :via => :get

  match 'posts/new' => 'posts#new', :as => 'new_post', :via => :get

  match 'posts' => 'posts#create', :as => 'create_post', :via => :post

  match 'posts/:id' => 'posts#show', :as => 'post', :via => :get

  match 'posts/:id' => 'posts#destroy', :as => 'delete_post', :via => :delete

  match 'posts/:id/edit' => 'posts#edit', :as => 'edit_post', :via => :get

  match 'posts/:id' => 'posts#update', :as => 'update_post', :via => :put

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title
  validates :title, :content, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  #Technically none of these actions are actually required
  #because they contain no code, however they do serve as
  #documentation for our project

  def index
  end #loads the app/views/info/index.html.erb

  def about
  end #loads the app/views/info/about.html.erb

  def contact
  end #loads the app/views/info/contact.html.erb
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order('created_at DESC')
  end #loads app/views/posts/index.html.erb

  def show
    @post = Post.find(params[:id])
  end #loads app/views/posts/show.html.erb

  def new
    @post = Post.new
  end #loads app/views/posts/new.html.erb

  def create
    @post = Post.new(params[:post])

    if @post.save
      #redirect to index action
      redirect_to :action => :index #redirects to new page and leaves state forgetting everything in @post
    else
      #@post.title = "" #removes title prior to putting things back in the form
      #load up the view associated with the new action
      render :action => :new #keeps state and remembers @post and puts the data back into the form
    end
  end #On success redirects to index else uses app/views/posts/new.html.erb

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to :action => :index
  end #No destroy.html.erb needs to exist, we always redirect

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    #@post.title = params[:title]
    #@post.content = params[:content]
    @post.update_attributes(params[:post])
    if @post.save
      #redirect to index action
      redirect_to :action => :index #redirects to new page and leaves state forgetting everything in @post
    else
      #@post.title = "" #removes title prior to putting things back in the form
      #load up the view associated with the new action
      render :action => :edit #keeps state and remembers @post and puts the data back into the form
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/info/about.html.erb
<h2>About Us</h2>
<p>Nullam eu varius elit, vel sodales erat. In hac habitasse platea dictumst. Curabitur suscipit lorem ac mi sagittis rhoncus. Aliquam et turpis non dui accumsan tincidunt varius nec tortor. Integer ultricies fringilla diam sed facilisis. Fusce laoreet, nibh vitae ullamcorper pulvinar, magna ipsum iaculis leo, at pulvinar ante massa at leo. Donec ligula leo, elementum eget purus non, eleifend lobortis mi. Etiam eget vestibulum est. Praesent pellentesque dui at ipsum tempor, nec facilisis velit egestas. Vestibulum pharetra quam purus, ut venenatis nulla suscipit eu. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>

app/views/info/contact.html.erb
<h2>Contact Us</h2>
<p>Cras tincidunt ut odio in pretium. Morbi nunc diam, tincidunt nec euismod nec, scelerisque eu massa. Suspendisse a porta arcu. Proin elit nisi, varius vel velit a, pulvinar fermentum nibh. Nulla eros lacus, aliquet at diam sed, dictum consequat turpis. Nam euismod sollicitudin lacus, nec elementum metus sollicitudin vel. Nulla facilisi. Praesent at purus fermentum, feugiat felis id, pulvinar sapien.</p>

app/views/info/index.html.erb
<h2>Home Page</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut dui porttitor mi viverra egestas at quis ante. Suspendisse ut orci nec justo euismod ullamcorper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam sodales urna at varius aliquam. In nibh purus, dictum in est a, cursus sagittis orci. Etiam non hendrerit dolor, non euismod lacus. Aenean ultricies volutpat turpis eu facilisis. Donec faucibus consequat ipsum, a varius magna tempus eu. Proin a vestibulum mauris. Nullam sed quam vitae massa egestas imperdiet. Quisque et dui eget lacus cursus posuere nec nec quam. Donec pretium ac metus rhoncus tristique. Vestibulum interdum nulla eget lectus mattis condimentum. Etiam leo tellus, sollicitudin ut dictum nec, volutpat sed libero. Donec ultricies pellentesque neque, id laoreet diam feugiat at. Etiam luctus mauris eu porta viverra.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>NonScaffoldedExample</title>
      <%= stylesheet_link_tag    "application", :media => "all" %>
      <%= javascript_include_tag "application" %>
      <%= csrf_meta_tags %>
    </head>
    <body>
        <header>
          <%= image_tag 'rails.png' %>
        </header>
        <!-- The second argument of link_to is always the route name followed by _path-->
        <ul id="menu">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'About Us', about_path %></li>
          <li><%= link_to 'Contact Us', contact_path %></li>
          <li><%= link_to 'Blog', posts_path %></li>
        </ul>
        <!-- this is where each view is injected -->
        <%= yield %>

    </body>
</html>

app/views/posts/_form.html.erb
<!-- the f block param is called a form building
     it will help us build our form
     f is aware that a post has a tile and a content -->
<%= form_for post do |f| %>
    <% if post.errors.any? %>
        <p style="color:red">All posts require a title and content.</p>
    <% end %>
    <div>
      <%= f.label :title %> <!-- generates an html label element -->
      <br/>
      <%= f.text_field :title %> <!-- generates an html input element -->
    </div>
    <div>
      <%= f.label :content %> <!-- generates an html label element -->
      <br/>
      <%= f.text_area :content %> <!-- generates an html text area element -->
    </div>
    <div>
      <%= f.submit %>
    </div>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit Blog Post</h2>

<%= render :partial => 'form', :locals => { :post => @post } %>

app/views/posts/index.html.erb
<h2>Company Blog</h2>

<!-- Loop through all the available blog posts -->
<% @posts.each do |post| %>
    <article>
        <h3><%=link_to post.title, post_path(post)%></h3>
        <div><%= post.content %></div>
        <p>
          <%= link_to 'Delete This Post', post, :method => :delete, :data => {:confirm => 'Are you sure?'} %>
          <%= link_to 'Edit This Post', edit_post_path(post) %>
        </p>
    </article>
<% end %>

<p><%= link_to 'Create New Blog Post', new_post_path %></p>

app/views/posts/new.html.erb
<h2>Create a New Blog Post</h2>

<%= render :partial => 'form', :locals => { :post => @post } %>

app/views/posts/show.html.erb
<h2>Company Blog</h2>

<article>
  <h3><%= @post.title %></h3>
  <p><%= @post.content %></p>
</article>